#pragma once
#define EVENT_INPUT				F("input") // input?=0/1/c:action1;action2;...
#define EVENT_OUTPUT			F("output") // output?=0/1/c:action1;action2;...
#define EVENT_COUNTER			F("counter") // counter?>n:action1;action2;...
#define EVENT_ADC					F("adc") // adc<>n:action1;action2;...
#define EVENT_TEMPERATURE	F("temperature") // temperature<>n:action1;action2;...
#define EVENT_HUMIDITY		F("humidity") // humidity<>n:action1;action2;...
#define EVENT_CO2					F("co2") // co2<>n:action1;action2;...
