#pragma once
#define SHEDULE_DAILY		F("daily@") // daily@hh:mm;action1;action2;...
#define SHEDULE_WEEKLY	F("weekly@") // weekly@week_day hh:mm;action1;action2;...
#define SHEDULE_MONTHLY	F("monthly@") // monthly@month_day hh:mm;action1;action2;...
#define SHEDULE_ONCE		F("once@") // once@yyyy.mm.dd hh:mm;action1;action2;...
